import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/NavBar";
import Footer from "@/components/ui/Footer";
import AuthProvider from "./context/AuthContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <AuthProvider>
            <Navbar></Navbar>

            <div className="px-4 sm:px-6 lg:px-8">{children}</div>
            <Toaster></Toaster>
            <Footer></Footer>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
